//! 便笺 20 色调色板（02 §5 / 06 §1.2–1.3）：10 个色相 × 浅/浓两档。
//! Rust 侧只需要 `paper`（窗体背景色）和 `dot`（托盘/强调），其余角色由 WebView 渲染。

use serde::{Deserialize, Serialize};

/// Generated by `packages/tokens` (Style Dictionary); committed under `packages/tokens/dist/`.
#[allow(dead_code)]
pub mod tokens {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../packages/tokens/dist/tokens.rs"
    ));
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum NoteColor {
    // 浅色档
    #[default]
    Graphite,
    Rose,
    Coral,
    Amber,
    Citron,
    Fern,
    Teal,
    Azure,
    Violet,
    Fuchsia,
    // 浓色档
    Slate,
    Carmine,
    Vermilion,
    Ochre,
    Olive,
    Pine,
    Peacock,
    Indigo,
    Wisteria,
    Eggplant,
}

impl NoteColor {
    pub const ALL: [NoteColor; 20] = [
        NoteColor::Graphite,
        NoteColor::Rose,
        NoteColor::Coral,
        NoteColor::Amber,
        NoteColor::Citron,
        NoteColor::Fern,
        NoteColor::Teal,
        NoteColor::Azure,
        NoteColor::Violet,
        NoteColor::Fuchsia,
        NoteColor::Slate,
        NoteColor::Carmine,
        NoteColor::Vermilion,
        NoteColor::Ochre,
        NoteColor::Olive,
        NoteColor::Pine,
        NoteColor::Peacock,
        NoteColor::Indigo,
        NoteColor::Wisteria,
        NoteColor::Eggplant,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            NoteColor::Graphite => "graphite",
            NoteColor::Rose => "rose",
            NoteColor::Coral => "coral",
            NoteColor::Amber => "amber",
            NoteColor::Citron => "citron",
            NoteColor::Fern => "fern",
            NoteColor::Teal => "teal",
            NoteColor::Azure => "azure",
            NoteColor::Violet => "violet",
            NoteColor::Fuchsia => "fuchsia",
            NoteColor::Slate => "slate",
            NoteColor::Carmine => "carmine",
            NoteColor::Vermilion => "vermilion",
            NoteColor::Ochre => "ochre",
            NoteColor::Olive => "olive",
            NoteColor::Pine => "pine",
            NoteColor::Peacock => "peacock",
            NoteColor::Indigo => "indigo",
            NoteColor::Wisteria => "wisteria",
            NoteColor::Eggplant => "eggplant",
        }
    }

    /// 浓淡档；与 `packages/shared` 的 `NOTE_COLOR_INFO.tier` 逐项一致。
    /// 浓色档的纸更深、彩度更高，验收门槛因此不同（见下面的测试）。
    pub fn is_deep(self) -> bool {
        matches!(
            self,
            NoteColor::Slate |
            NoteColor::Carmine |
            NoteColor::Vermilion |
            NoteColor::Ochre |
            NoteColor::Olive |
            NoteColor::Pine |
            NoteColor::Peacock |
            NoteColor::Indigo |
            NoteColor::Wisteria |
            NoteColor::Eggplant
        )
    }

    /// Unknown values render as graphite (02 §3 meta.color rule).
    pub fn parse(s: &str) -> NoteColor {
        NoteColor::ALL
            .into_iter()
            .find(|c| c.as_str() == s)
            .unwrap_or(NoteColor::Graphite)
    }

    /// Windows Sticky Notes theme → palette (tools/export_sticky_notes.py THEME_MAP).
    pub fn from_plum_theme(theme: &str) -> NoteColor {
        match theme.trim().to_ascii_lowercase().as_str() {
            "yellow" => NoteColor::Citron,
            "green" => NoteColor::Fern,
            "blue" => NoteColor::Azure,
            "purple" => NoteColor::Violet,
            "pink" => NoteColor::Rose,
            "gray" | "grey" | "charcoal" => NoteColor::Graphite,
            _ => NoteColor::Citron,
        }
    }

    /// `paper` role: window background, from the generated design tokens.
    pub fn paper_rgb(self, dark: bool) -> (u8, u8, u8) {
        let rgb = tokens::note_paper(self.as_str(), dark);
        (rgb.r, rgb.g, rgb.b)
    }

    /// `dot` role (tray / accents), from the generated design tokens.
    pub fn dot_rgb(self, dark: bool) -> (u8, u8, u8) {
        let rgb = tokens::note_dot(self.as_str(), dark);
        (rgb.r, rgb.g, rgb.b)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_roundtrip() {
        for c in NoteColor::ALL {
            assert_eq!(NoteColor::parse(c.as_str()), c);
        }
        assert_eq!(NoteColor::parse("nope"), NoteColor::Graphite);
        assert_eq!(NoteColor::parse("eggplant"), NoteColor::Eggplant);
        assert_eq!(NoteColor::ALL.iter().filter(|c| c.is_deep()).count(), 10);
        assert_eq!(NoteColor::from_plum_theme("Yellow"), NoteColor::Citron);
        assert_eq!(NoteColor::from_plum_theme("Charcoal"), NoteColor::Graphite);
        assert_eq!(NoteColor::from_plum_theme(""), NoteColor::Citron);
    }

    /// sRGB 相对亮度（WCAG 2.x），只用于下面的设计不变量断言。
    fn luminance((r, g, b): (u8, u8, u8)) -> f64 {
        fn ch(v: u8) -> f64 {
            let v = f64::from(v) / 255.0;
            if v <= 0.040_45 {
                v / 12.92
            } else {
                ((v + 0.055) / 1.055).powf(2.4)
            }
        }
        0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b)
    }

    /// 颜色的**精确值**由 `packages/tokens/test/contrast.test.ts` 把关（对比度、色度、色差），
    /// Rust 侧只断言"生成的 token 确实接上了、且满足设计意图"，不再手抄一份 hex 对照表
    /// ——手抄表每次调色都会漏改，反而挡住真正的回归。
    #[test]
    fn tokens_match_design_intent() {
        for dark in [false, true] {
            let mut seen: Vec<(u8, u8, u8)> = Vec::new();
            for c in NoteColor::ALL {
                let paper = c.paper_rgb(dark);
                let dot = c.dot_rgb(dark);

                assert!(!seen.contains(&paper), "{c:?} dark={dark} 纸色与其它颜色重复");
                seen.push(paper);

                assert_ne!(paper, dot, "{c:?} dark={dark} 身份色与纸色相同");

                let l = luminance(paper);
                if dark {
                    assert!(l <= 0.075, "{c:?} 深色主题的纸太亮：{l:.4}");
                } else if c.is_deep() {
                    assert!(l >= 0.64, "{c:?} 浓色档的纸太暗：{l:.4}");
                    assert!(l <= 0.80, "{c:?} 浓色档的纸不够浓：{l:.4}");
                } else {
                    assert!(l >= 0.86, "{c:?} 浅色档的纸太暗：{l:.4}");
                }
            }
        }
    }

    /// 未知色回落到 graphite（02 §3），且默认色就是 graphite。
    #[test]
    fn default_is_graphite() {
        assert_eq!(NoteColor::default(), NoteColor::Graphite);
        assert_eq!(NoteColor::parse(""), NoteColor::Graphite);
        assert_eq!(NoteColor::parse("GRAPHITE"), NoteColor::Graphite);
    }
}
