// 与 tools/test_export_sticky_notes.py 合成库对应的 notes.json 形态（已删除的 n-004 不在文件内）。
export const plumExportFixture = {
  exported_at: "2025-09-01T00:00:00+00:00",
  source_db:
    "C:\\Users\\me\\AppData\\Local\\Packages\\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe\\LocalState\\plum.sqlite",
  count: 4,
  notes: [
    {
      external_id: "n-001",
      source: "plum.sqlite",
      title: "周三 14:00 产品评审",
      markdown: "周三 14:00 **产品评审**\n确认 OKLCH 色板 v2.3\n*下周补 macOS 验证*",
      text: "周三 14:00 产品评审\n确认 OKLCH 色板 v2.3\n下周补 macOS 验证",
      color: "citron",
      original_theme: "Yellow",
      pinned: true,
      is_open: true,
      window: { x: 340, y: 180, w: 320, h: 320, display_id: "{DISPLAY1}" },
      created_at: "2025-08-24T02:26:40+00:00",
      updated_at: "2025-09-02T08:40:00+00:00",
      attachments: [{ path: "media/abc123.png", mime: "image/png" }],
      has_ink: false,
      content_source: "Text",
      import_degraded: false,
    },
    {
      external_id: "n-003",
      source: "plum.sqlite",
      title: "服务器续费",
      markdown: "服务器续费\nHostinger KVM 4 到期 11/20",
      text: "服务器续费\nHostinger KVM 4 到期 11/20",
      color: "azure",
      original_theme: "Blue",
      pinned: false,
      is_open: false,
      window: { x: 900, y: 120, w: 220, h: 260, display_id: "{DISPLAY1}" },
      created_at: "2025-08-01T00:53:20+00:00",
      updated_at: "2025-08-25T06:13:20+00:00",
      attachments: [],
      has_ink: false,
      content_source: "LastServerVersion",
      import_degraded: false,
    },
    {
      external_id: "n-002",
      source: "plum.sqlite",
      title: "取快递",
      markdown: "取快递\n丰巢 8-2211，取件码 4471",
      text: "取快递\n丰巢 8-2211，取件码 4471",
      color: "rose",
      original_theme: "Pink",
      pinned: false,
      is_open: true,
      window: { x: -1600, y: -240, w: 180, h: 140, display_id: "{DISPLAY2}" },
      created_at: "2025-08-12T12:40:00+00:00",
      updated_at: "2025-08-18T07:33:20+00:00",
      attachments: [],
      has_ink: true,
      content_source: "Text",
      import_degraded: false,
    },
    {
      external_id: "n-005",
      source: "plum.sqlite",
      title: "买菜",
      markdown: "买菜\n西红柿 2 斤\n~~已买~~牛奶",
      text: "买菜\n西红柿 2 斤\n已买牛奶",
      color: "citron",
      original_theme: "Teal",
      pinned: false,
      is_open: true,
      window: null,
      created_at: null,
      updated_at: "2025-07-14T13:33:20+00:00",
      attachments: [],
      has_ink: false,
      content_source: "Text",
      import_degraded: true,
    },
  ],
};
